package com.example.ui.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Common & Navigation
    val appName: String = "VoiceKadai",
    val home: String = "Home",
    val khata: String = "Khata",
    val expenses: String = "Expenses",
    val reminders: String = "Reminders",
    val settings: String = "Settings",
    val subscription: String = "Subscription",
    val aiAssistant: String = "AI Assistant",
    val blueprint: String = "Blueprint",
    val cancel: String = "Cancel",
    val save: String = "Save",
    val done: String = "Done",
    val delete: String = "Delete",
    val edit: String = "Edit",
    val search: String = "Search",
    val all: String = "All",
    val back: String = "Back",
    val submit: String = "Submit",
    val optional: String = "Optional",
    val pro: String = "PRO",
    val free: String = "FREE",
    val active: String = "ACTIVE",

    // Auth Screen
    val signInTitle: String = "Sign In to Your Merchant Account",
    val signInSubtitle: String = "Sync your voice khata, ledgers & UPI reminders across devices",
    val signInGoogle: String = "Sign In with Google",
    val signInGoogleDesc: String = "Use your personal Google account (Free Plan)",
    val signInMicrosoft: String = "Sign In with Microsoft",
    val enterPhone: String = "Enter Mobile Number (WhatsApp/UPI)",
    val sendOtp: String = "Send Login OTP",
    val verifyOtp: String = "Verify OTP & Enter Kadai",
    val enterOtp: String = "Enter 4-digit SMS OTP",
    val enterStoreName: String = "Your Store / Business Name",
    val enterOwnerName: String = "Your Name (Owner)",
    val enterEmail: String = "Your Email Address",
    val continueWithAccount: String = "Continue to My Kadai",
    val exploreDemoStore: String = "Explore Demo Store as Guest",
    val authTagline: String = "Speak your business. We handle the records.",
    val authBadge: String = "Built for Indian MSME Merchants & Kirana Stores",

    // Dashboard
    val todaySales: String = "Today's Sales",
    val cashInflow: String = "Cash Inflow (Got)",
    val pendingUdhaar: String = "Pending Udhaar (You'll Get)",
    val advanceToGive: String = "Advance Paid (You'll Give)",
    val quickActions: String = "Quick Actions",
    val recordSale: String = "Record Sale",
    val recordExpense: String = "Record Expense",
    val sendWhatsAppReminder: String = "Send Reminder",
    val recentTransactions: String = "Recent Transactions",
    val viewAll: String = "View All",
    val noTransactionsYet: String = "No transactions recorded yet today.",
    val tapMicToSpeak: String = "Tap Mic & Speak in your language",
    val micCtaHint: String = "e.g. 'Kumar 500 udhaar', 'Ramesh gave 1200 cash'",
    val topDebtors: String = "Top Pending Balances",

    // Khata / Customers
    val customersTitle: String = "Customer Khata Directory",
    val searchCustomerHint: String = "Search customer name or phone...",
    val filterAll: String = "All",
    val filterUdhaar: String = "Pending Udhaar",
    val filterAdvance: String = "Advance",
    val filterSettled: String = "Settled",
    val addCustomer: String = "Add Customer",
    val customerName: String = "Customer Name",
    val phoneNumber: String = "Phone Number",
    val openingBalance: String = "Opening Balance (₹)",
    val notes: String = "Notes (e.g. address, landmark)",
    val balanceDue: String = "Balance Due",
    val advanceBalance: String = "Advance Balance",
    val settledAccount: String = "Settled (₹0)",
    val call: String = "Call",
    val whatsapp: String = "WhatsApp",
    val noCustomersFound: String = "No customers found matching criteria.",

    // Customer Detail
    val gaveCredit: String = "Gave Credit (Udhaar -)",
    val gotPayment: String = "Got Payment (Jama +)",
    val transactionHistory: String = "Transaction History",
    val sendPaymentReminder: String = "Send Payment Link on WhatsApp",
    val settleAccount: String = "Settle Account",
    val enterAmount: String = "Enter Amount (₹)",
    val recordEntry: String = "Record Entry",
    val enterNote: String = "Note (e.g. Rice 5kg, Oil 1L)",

    // Expenses
    val expensesTitle: String = "Business Expenses (செலவுகள்)",
    val todayExpenseTotal: String = "Today's Expenses",
    val totalExpenseMonth: String = "Total Expenses",
    val addExpenseTitle: String = "Record Shop Expense",
    val expenseCategory: String = "Category",
    val paymentMode: String = "Payment Mode",
    val catStock: String = "Stock & Inventory",
    val catRent: String = "Shop Rent",
    val catElectricity: String = "Electricity & Utility",
    val catTea: String = "Tea, Snacks & Food",
    val catTransport: String = "Transport & Delivery",
    val catSalary: String = "Staff Salary",
    val catOther: String = "Other Expense",

    // Reminders
    val remindersTitle: String = "Smart Payment Reminders",
    val pendingReminders: String = "Pending Reminders",
    val completedReminders: String = "Completed",
    val scheduleReminder: String = "Schedule Reminder",
    val markAsDone: String = "Mark as Done",
    val sendViaWhatsApp: String = "Send via WhatsApp",

    // AI Chat & Analytics
    val aiTitle: String = "AI Business Assistant",
    val aiSubtitle: String = "Instant deterministic financial insights & reports",
    val aiPromptHint: String = "Ask in Tamil, Tanglish, Hindi or English...",
    val promptProfit: String = "What is today's net profit?",
    val promptTopDebtors: String = "Who owes me the most money?",
    val promptWeeklySales: String = "Weekly sales summary",
    val promptExpensesBreakdown: String = "Breakdown of today's expenses",
    val clearChat: String = "Clear Chat",

    // Subscription
    val subscriptionTitle: String = "Subscription Plans",
    val freePlanName: String = "Free Plan",
    val freePlanPrice: String = "₹0",
    val freePlanCycle: String = "Forever Free",
    val freePlanFeat1: String = "50 voice commands/month",
    val freePlanFeat2: String = "Basic customer records",
    val freePlanFeat3: String = "Basic dashboard",
    val proPlanName: String = "Pro Plan",
    val proPlanPrice: String = "₹299",
    val proPlanAnnual: String = "₹2,499",
    val proPlanCycle: String = "/month",
    val proPlanFeat1: String = "Unlimited voice commands",
    val proPlanFeat2: String = "AI business reports",
    val proPlanFeat3: String = "Smart reminders",
    val proPlanFeat4: String = "Advanced analytics",
    val proPlanFeat5: String = "Multiple languages",
    val bizPlanName: String = "Business Plan",
    val bizPlanPrice: String = "₹999",
    val bizPlanAnnual: String = "₹7,999",
    val bizPlanCycle: String = "/month",
    val bizPlanFeat1: String = "Multiple employees",
    val bizPlanFeat2: String = "Multiple devices",
    val bizPlanFeat3: String = "Advanced reports",
    val bizPlanFeat4: String = "Data backup",
    val bizPlanFeat5: String = "Business analytics",
    val monthlyBilling: String = "Monthly Billing",
    val annualBilling: String = "Annual (Save 30%)",
    val subscribeNow: String = "Subscribe to Plan",
    val currentActivePlan: String = "Current Active Plan",
    val playStorePayoutNotice: String = "When published on Play Store, In-App Subscriptions revenue goes directly to the developer's registered merchant account.",

    // Settings
    val settingsTitle: String = "Store & Account Settings",
    val profileSection: String = "Merchant Profile",
    val languageSection: String = "Voice & App Display Language",
    val safetyGateTitle: String = "Zero-Hallucination Safety Gate",
    val safetyGateSubtitle: String = "Visual verification before saving ledger",
    val signOutButton: String = "Sign Out / Switch Account",
    val signOutDialogTitle: String = "Sign Out of VoiceKadai?",
    val signOutDialogText: String = "You will return to the sign-in screen. Your local database remains secure.",

    // Voice Sheet & Safety Gate
    val listeningTitle: String = "Listening...",
    val listeningHint: String = "Speak in Tamil, Tanglish, Hindi or English",
    val processingVoice: String = "AI processing transcript...",

    // Play Store Feedback & Rating
    val playStoreReviewTitle: String = "Enjoying VoiceKadai?",
    val playStoreReviewSubtitle: String = "You've been managing your Kadai for over 1 minute! If VoiceKadai is helping your shop, please take 5 seconds to rate us on Google Play.",
    val playStoreRating5Title: String = "Loved it! 5 Stars ⭐⭐⭐⭐⭐",
    val playStoreRating4Title: String = "Great App! 4 Stars ⭐⭐⭐⭐",
    val playStoreRating3Title: String = "Good, needs improvements ⭐⭐⭐",
    val playStoreRatingLowTitle: String = "Tell us how to improve ⭐",
    val rateOnPlayStore: String = "Rate on Google Play Store",
    val submitFeedback: String = "Submit Feedback",
    val remindMeLater: String = "Remind Me Later",
    val notNow: String = "Not Now",
    val feedbackPrompt: String = "How can we make VoiceKadai better for your shop?",
    val feedbackPlaceholder: String = "Type your suggestions, wanted voice commands, or feature requests here...",
    val feedbackSentToast: String = "Thank you! Your feedback helps make VoiceKadai better for Indian merchants. 🙏",
    val ratePlayStoreCardTitle: String = "Rate VoiceKadai on Google Play",
    val ratePlayStoreCardSubtitle: String = "Support our mission to empower Kirana & MSME stores with voice AI"
) {
    val gaveUdhaar: String get() = gaveCredit
    val gotJama: String get() = gotPayment
    val addExpense: String get() = recordExpense
    val allCustomers: String get() = customersTitle
    val searchPlaceholder: String get() = searchCustomerHint
    val noCustomersYet: String get() = noCustomersFound
    val zeroHallucination: String get() = safetyGateTitle
    val safetyGateDesc: String get() = safetyGateSubtitle
    val languageSelection: String get() = languageSection
    val signOut: String get() = signOutButton
}

fun getAppStrings(language: String?): AppStrings {
    val lang = language?.lowercase() ?: "tanglish"
    return when {
        lang.contains("தமிழ்") || lang.contains("pure tamil") || lang == "tamil" -> TamilStrings
        lang.contains("tanglish") -> TanglishStrings
        lang.contains("हिंदी") || lang.contains("hindi") || lang.contains("hinglish") -> HindiStrings
        else -> EnglishStrings
    }
}

val EnglishStrings = AppStrings()

val TamilStrings = AppStrings(
    appName = "VoiceKadai (வாய்ஸ்கடை)",
    home = "முகப்பு",
    khata = "காதா புத்தகம்",
    expenses = "செலவுகள்",
    reminders = "நினைவூட்டல்",
    settings = "அமைப்புகள்",
    subscription = "சந்தா திட்டம்",
    aiAssistant = "AI உதவியாளர்",
    blueprint = "கட்டமைப்பு",
    cancel = "ரத்து",
    save = "சேமி",
    done = "முடிந்தது",
    delete = "நீக்கு",
    edit = "திருத்து",
    search = "தேடுக",
    all = "அனைத்தும்",
    back = "பின்செல்",
    submit = "சமர்ப்பி",
    optional = "விருப்பத்தேர்வு",
    pro = "ப்ரோ",
    free = "இலவசம்",
    active = "செயலில்",

    // Auth
    signInTitle = "உங்கள் கடை கணக்கில் உள்நுழைக",
    signInSubtitle = "உங்கள் வாய்ஸ் காதா, லெட்ஜர் & UPI நினைவூட்டல்களை ஒத்திசைக்கவும்",
    signInGoogle = "கூகிள் மூலம் உள்நுழைக",
    signInGoogleDesc = "உங்கள் சொந்த கூகிள் கணக்கை பயன்படுத்துங்கள் (இலவச திட்டம்)",
    signInMicrosoft = "மைக்ரோசாப்ட் மூலம் உள்நுழைக",
    enterPhone = "மொபைல் எண் (வாட்ஸ்அப்/UPI)",
    sendOtp = "OTP குறியீடு அனுப்புக",
    verifyOtp = "OTP சரிபார்த்து உள்ளே செல்க",
    enterOtp = "4-இலக்க SMS OTP குறியீடு",
    enterStoreName = "உங்கள் கடையின் பெயர்",
    enterOwnerName = "உங்கள் பெயர் (உரிமையாளர்)",
    enterEmail = "மின்னஞ்சல் முகவரி",
    continueWithAccount = "கடைக்குள் நுழைக",
    exploreDemoStore = "டெமோ கடையை பார்வையிடுக",
    authTagline = "வாய்ஸில் பேசுங்கள். கணக்கை நாங்கள் பார்த்துக் கொள்கிறோம்.",
    authBadge = "இந்திய சிறு வணிகர்கள் & மளிகைக் கடைகளுக்காக உருவாக்கப்பட்டது",

    // Dashboard
    todaySales = "இன்றைய விற்பனை",
    cashInflow = "பெற்ற ரொக்கம் (வரவு)",
    pendingUdhaar = "வர வேண்டிய கடன் (உதார்)",
    advanceToGive = "கொடுக்க வேண்டிய முன்பணம்",
    quickActions = "விரைவுச் செயல்கள்",
    recordSale = "விற்பனை பதிவு",
    recordExpense = "செலவு பதிவு",
    sendWhatsAppReminder = "நினைவூட்டல் அனுப்ப",
    recentTransactions = "சமீபத்திய பரிவர்த்தனைகள்",
    viewAll = "அனைத்தும் காண்க",
    noTransactionsYet = "இன்று இதுவரை எந்த பரிவர்த்தனையும் இல்லை.",
    tapMicToSpeak = "மைக் தொட்டு உங்கள் மொழியில் பேசுங்கள்",
    micCtaHint = "எ.கா: 'குமார் 500 கடன்', 'ரமேஷ் 1200 ரொக்கம் தந்தார்'",
    topDebtors = "அதிக பாக்கி வைத்துள்ள வாடிக்கையாளர்கள்",

    // Khata
    customersTitle = "வாடிக்கையாளர் காதா பட்டியல்",
    searchCustomerHint = "பெயர் அல்லது மொபைல் எண் தேடுக...",
    filterAll = "அனைத்தும்",
    filterUdhaar = "வர வேண்டிய கடன்",
    filterAdvance = "முன்பணம்",
    filterSettled = "கணக்கு முடிந்தது",
    addCustomer = "புதிய வாடிக்கையாளர்",
    customerName = "வாடிக்கையாளர் பெயர்",
    phoneNumber = "தொலைபேசி எண்",
    openingBalance = "தொடக்க இருப்பு (₹)",
    notes = "குறிப்புகள் (எ.கா: முகவரி, தெரு)",
    balanceDue = "வர வேண்டிய பாக்கி",
    advanceBalance = "முன்பண இருப்பு",
    settledAccount = "பாக்கி இல்லை (₹0)",
    call = "அழைக்க",
    whatsapp = "வாட்ஸ்அப்",
    noCustomersFound = "வாடிக்கையாளர்கள் எவரும் இல்லை.",

    // Customer Detail
    gaveCredit = "கடன் கொடுத்தது (உதார் -)",
    gotPayment = "பணம் பெற்றது (வரவு +)",
    transactionHistory = "பரிவர்த்தனை வரலாறு",
    sendPaymentReminder = "வாட்ஸ்அப்பில் பேமெண்ட் லிங்க் அனுப்புக",
    settleAccount = "முழுக் கணக்கை முடிக்க",
    enterAmount = "தொகை (₹)",
    recordEntry = "பதிவு செய்க",
    enterNote = "பொருள் குறிப்பு (எ.கா: அரிசி 5 கிலோ, எண்ணெய்)",

    // Expenses
    expensesTitle = "கடைச் செலவுகள்",
    todayExpenseTotal = "இன்றைய செலவு",
    totalExpenseMonth = "மொத்த செலவுகள்",
    addExpenseTitle = "கடைச் செலவு பதிவு செய்க",
    expenseCategory = "செலவு வகை",
    paymentMode = "பணம் செலுத்திய முறை",
    catStock = "சரக்கு & பொருட்கள்",
    catRent = "கடை வாடகை",
    catElectricity = "மின்சார கட்டணம்",
    catTea = "டீ, காபி & உணவு",
    catTransport = "போக்குவரத்து & டெலிவரி",
    catSalary = "வேலையாள் சம்பளம்",
    catOther = "மற்ற இதர செலவுகள்",

    // Reminders
    remindersTitle = "ஸ்மார்ட் கடன் நினைவூட்டல்கள்",
    pendingReminders = "நிலுவையில் உள்ள நினைவூட்டல்",
    completedReminders = "முடிந்தவை",
    scheduleReminder = "நினைவூட்டல் அமை",
    markAsDone = "முடிந்தது என குறி",
    sendViaWhatsApp = "வாட்ஸ்அப் மூலம் அனுப்புக",

    // AI Chat
    aiTitle = "AI கடை உதவியாளர்",
    aiSubtitle = "உடனடி நிதி மற்றும் கணக்கு அறிக்கைகள்",
    aiPromptHint = "தமிழில் உங்கள் கடை கணக்கு பற்றி கேளுங்கள்...",
    promptProfit = "இன்றைய நிகர லாபம் எவ்வளவு?",
    promptTopDebtors = "அதிக கடன் வைத்திருப்பவர் யார்?",
    promptWeeklySales = "இந்த வார விற்பனை சுருக்கம்",
    promptExpensesBreakdown = "இன்றைய செலவு விவரங்கள்",
    clearChat = "சாட் அழிக்க",

    // Subscription
    subscriptionTitle = "சந்தா திட்டங்கள்",
    freePlanName = "இலவச திட்டம்",
    freePlanPrice = "₹0",
    freePlanCycle = "வாழ்நாள் இலவசம்",
    freePlanFeat1 = "மாதம் 50 வாய்ஸ் கட்டளைகள்",
    freePlanFeat2 = "அடிப்படை வாடிக்கையாளர் பதிவுகள்",
    freePlanFeat3 = "அடிப்படை டாஷ்போர்டு",
    proPlanName = "ப்ரோ திட்டம்",
    proPlanPrice = "₹299",
    proPlanAnnual = "₹2,499",
    proPlanCycle = "/மாதம்",
    proPlanFeat1 = "வரம்பற்ற வாய்ஸ் கட்டளைகள்",
    proPlanFeat2 = "AI வணிக அறிக்கைகள்",
    proPlanFeat3 = "ஸ்மார்ட் நினைவூட்டல்கள்",
    proPlanFeat4 = "மேம்பட்ட பகுப்பாய்வு",
    proPlanFeat5 = "பல மொழிகள் ஆதரவு",
    bizPlanName = "வணிக திட்டம்",
    bizPlanPrice = "₹999",
    bizPlanAnnual = "₹7,999",
    bizPlanCycle = "/மாதம்",
    bizPlanFeat1 = "பல பணியாளர்கள்",
    bizPlanFeat2 = "பல சாதனங்கள் நேரலை ஒத்திசைவு",
    bizPlanFeat3 = "மேம்பட்ட அறிக்கைகள்",
    bizPlanFeat4 = "கிளவுட் தரவு காப்புப்பிரதி",
    bizPlanFeat5 = "வணிக பகுப்பாய்வு",
    monthlyBilling = "மாதாந்திர கட்டணம்",
    annualBilling = "வருடாந்திரம் (30% சேமிப்பு)",
    subscribeNow = "சந்தா செலுத்துக",
    currentActivePlan = "தற்போது செயலில் உள்ள திட்டம்",
    playStorePayoutNotice = "Play Store-ல் வெளியிடும் போது, சந்தா வருமானம் நேரடியாக டெவலப்பரின் வங்கிக் கணக்கில் வரவு வைக்கப்படும்.",

    // Settings
    settingsTitle = "கடை & கணக்கு அமைப்புகள்",
    profileSection = "வணிகர் சுயவிவரம்",
    languageSection = "குரல் & செயலி காட்சி மொழி",
    safetyGateTitle = "Zero-Hallucination பாதுகாப்பு வாயில்",
    safetyGateSubtitle = "சேமிக்கும் முன் திரையில் உறுதிப்படுத்தல்",
    signOutButton = "வெளியேறு / கணக்கை மாற்று",
    signOutDialogTitle = "VoiceKadai-லிருந்து வெளியேறவா?",
    signOutDialogText = "உங்கள் ஆஃப்லைன் தரவு பாதுகாப்பாக சேமிக்கப்பட்டுள்ளது.",

    // Play Store Review
    playStoreReviewTitle = "வாய்ஸ்கடை பயனுள்ளதாக உள்ளதா?",
    playStoreReviewSubtitle = "நீங்கள் 1 நிமிடத்திற்கும் மேலாக வாய்ஸ்கடையை பயன்படுத்தி வருகிறீர்கள்! உங்கள் கடைக்கு பயனுள்ளதாக இருந்தால் Google Play-ல் 5-Star ரேட்டிங் வழங்குங்கள்.",
    playStoreRating5Title = "மிகவும் பிடித்திருக்கிறது! 5 Stars ⭐⭐⭐⭐⭐",
    playStoreRating4Title = "சிறந்த செயலி! 4 Stars ⭐⭐⭐⭐",
    playStoreRating3Title = "நன்று, முன்னேற்றம் தேவை ⭐⭐⭐",
    playStoreRatingLowTitle = "உங்கள் ஆலோசனையை சொல்லுங்கள் ⭐",
    rateOnPlayStore = "Google Play-ல் ரேட்டிங் செய்க",
    submitFeedback = "கருத்து அனுப்புக",
    remindMeLater = "பின்னர் நினைவூட்டு",
    notNow = "இப்போது வேண்டாம்",
    feedbackPrompt = "வாய்ஸ்கடையை மேலும் சிறப்பாக்க என்ன செய்ய வேண்டும்?",
    feedbackPlaceholder = "உங்கள் ஆலோசனைகள் மற்றும் குரல் கட்டளை தேவைகளை இங்கே பதிவிடவும்...",
    feedbackSentToast = "நன்றி! உங்கள் கருத்து வாய்ஸ்கடையை மேம்படுத்த உதவும். 🙏",
    ratePlayStoreCardTitle = "Google Play-ல் ரேட்டிங் செய்க",
    ratePlayStoreCardSubtitle = "சிறு வணிகர்களுக்கான குரல் AI தொழில்நுட்பத்தை ஆதரிக்கவும்"
)

val TanglishStrings = AppStrings(
    appName = "VoiceKadai",
    home = "Home",
    khata = "Khata",
    expenses = "Selavugal (Expenses)",
    reminders = "Reminders",
    settings = "Settings",
    subscription = "Subscription",
    aiAssistant = "AI Assistant",
    blueprint = "Blueprint",
    cancel = "Cancel",
    save = "Save Pannu",
    done = "Mudinjadhu",
    delete = "Delete",
    edit = "Edit",
    search = "Theduga (Search)",
    all = "Ellaam",
    back = "Pinnaadi (Back)",
    submit = "Submit",
    optional = "Optional",
    pro = "PRO",
    free = "FREE",
    active = "ACTIVE",

    // Auth
    signInTitle = "Sign In to Your Merchant Account",
    signInSubtitle = "Sync your voice khata, ledgers & WhatsApp reminders",
    signInGoogle = "Google Moolam Sign In",
    signInGoogleDesc = "Unga Google account vachu login pannunga (Free Plan)",
    signInMicrosoft = "Microsoft Moolam Sign In",
    enterPhone = "Mobile Number (WhatsApp/UPI)",
    sendOtp = "Send OTP",
    verifyOtp = "Verify OTP & Enter Kadai",
    enterOtp = "Enter 4-digit SMS OTP",
    enterStoreName = "Unga Kadai Peyar (Store Name)",
    enterOwnerName = "Unga Peyar (Owner Name)",
    enterEmail = "Email Address",
    continueWithAccount = "Kadai-kulla Pogavum",
    exploreDemoStore = "Demo Kadai Explore Pannunga",
    authTagline = "Vaayila pesunga. Kadai kanakku naanga paathukkurom.",
    authBadge = "Built for Indian MSME Merchants & Kirana Stores",

    // Dashboard
    todaySales = "Innaiki Sales",
    cashInflow = "Vandha Panam (Got)",
    pendingUdhaar = "Vara vendiya Udhaar (Get)",
    advanceToGive = "Thara vendiya Advance (Give)",
    quickActions = "Quick Actions",
    recordSale = "Sale Entry",
    recordExpense = "Selavu Entry",
    sendWhatsAppReminder = "Reminder Anupu",
    recentTransactions = "Recent Transactions",
    viewAll = "Ellaam Paaru",
    noTransactionsYet = "Innaiki innum transaction ethuvum illa.",
    tapMicToSpeak = "Mic thottu unga mozhiyila pesunga",
    micCtaHint = "e.g. 'Kumar kitta 500 udhaar', 'Ramesh 1200 cash thandharu'",
    topDebtors = "Adhiga Udhaar Customers",

    // Khata
    customersTitle = "Customer Khata Directory",
    searchCustomerHint = "Peyar or phone theduga...",
    filterAll = "Ellaam",
    filterUdhaar = "Udhaar Mattum",
    filterAdvance = "Advance Mattum",
    filterSettled = "Mudinjadhu (Settled)",
    addCustomer = "Pudhu Customer",
    customerName = "Customer Peyar",
    phoneNumber = "Phone Number",
    openingBalance = "Starting Balance (₹)",
    notes = "Notes (e.g. Street, Address)",
    balanceDue = "Vara vendiya Baaki",
    advanceBalance = "Advance Iruppu",
    settledAccount = "Baaki Illai (₹0)",
    call = "Call",
    whatsapp = "WhatsApp",
    noCustomersFound = "Endha customer-um illai.",

    // Customer Detail
    gaveCredit = "Udhaar Kuduthen (Gave -)",
    gotPayment = "Panam Vandhadhu (Got +)",
    transactionHistory = "Transaction History",
    sendPaymentReminder = "WhatsApp-la Payment Link Anupu",
    settleAccount = "Kanakka Mudikka (Settle)",
    enterAmount = "Amount (₹)",
    recordEntry = "Record Entry",
    enterNote = "Note (e.g. Arisi 5kg, Oil)",

    // Expenses
    expensesTitle = "Kadai Selavugal (Expenses)",
    todayExpenseTotal = "Innaiki Selavu",
    totalExpenseMonth = "Total Selavugal",
    addExpenseTitle = "Pudhu Selavu Entry",
    expenseCategory = "Selavu Category",
    paymentMode = "Payment Mode",
    catStock = "Sarakku & Provision Stock",
    catRent = "Kadai Vaadagai (Rent)",
    catElectricity = "Current Bill (Electricity)",
    catTea = "Tea, Tiffin & Snacks",
    catTransport = "Auto / Delivery Transport",
    catSalary = "Staff Salary",
    catOther = "Matra Selavugal",

    // Reminders
    remindersTitle = "Smart Payment Reminders",
    pendingReminders = "Pending Reminders",
    completedReminders = "Mudinjadhu (Completed)",
    scheduleReminder = "Set Reminder",
    markAsDone = "Mark Done",
    sendViaWhatsApp = "WhatsApp Moolam Anupu",

    // AI Chat
    aiTitle = "AI Kadai Assistant",
    aiSubtitle = "Instant business insights & kanakkugal",
    aiPromptHint = "Tamil or English-la unga kadai pathi kelunga...",
    promptProfit = "Innaiki net profit evalo?",
    promptTopDebtors = "Yaaru kitta adhiga udhaar irukku?",
    promptWeeklySales = "This week sales summary sollunga",
    promptExpensesBreakdown = "Innaiki selavu details enna?",
    clearChat = "Chat Clear Pannu",

    // Subscription
    subscriptionTitle = "Subscription Plans",
    freePlanName = "Free Plan",
    freePlanPrice = "₹0",
    freePlanCycle = "Forever Free",
    freePlanFeat1 = "50 voice commands/month",
    freePlanFeat2 = "Basic customer records",
    freePlanFeat3 = "Basic dashboard",
    proPlanName = "Pro Plan",
    proPlanPrice = "₹299",
    proPlanAnnual = "₹2,499",
    proPlanCycle = "/month",
    proPlanFeat1 = "Unlimited voice commands",
    proPlanFeat2 = "AI business reports",
    proPlanFeat3 = "Smart reminders",
    proPlanFeat4 = "Advanced analytics",
    proPlanFeat5 = "Multiple languages",
    bizPlanName = "Business Plan",
    bizPlanPrice = "₹999",
    bizPlanAnnual = "₹7,999",
    bizPlanCycle = "/month",
    bizPlanFeat1 = "Multiple employees",
    bizPlanFeat2 = "Multiple devices live sync",
    bizPlanFeat3 = "Advanced reports",
    bizPlanFeat4 = "Cloud data backup",
    bizPlanFeat5 = "Business analytics",
    monthlyBilling = "Monthly Billing",
    annualBilling = "Annual (Save 30%)",
    subscribeNow = "Subscribe Pannunga",
    currentActivePlan = "Current Active Plan",
    playStorePayoutNotice = "Play Store subscriptions direct-ah Developer's registered bank account-ku pogum.",

    // Settings
    settingsTitle = "Store & Account Settings",
    profileSection = "Merchant Profile",
    languageSection = "Voice & App Display Language",
    safetyGateTitle = "Zero-Hallucination Safety Gate",
    safetyGateSubtitle = "Save pannurathukku munnadi screen-la verify pannunga",
    signOutButton = "Sign Out / Switch Account",
    signOutDialogTitle = "VoiceKadai-la irundhu Sign Out pannava?",
    signOutDialogText = "Unga offline database safe-ah irukkum.",

    // Play Store Review
    playStoreReviewTitle = "VoiceKadai pudichurukka?",
    playStoreReviewSubtitle = "1 minute-ku mela VoiceKadai use pannuringa! Unga kadai-ku use-ah irundha Google Play-la 5 Stars rating kudunga.",
    playStoreRating5Title = "Super App! 5 Stars ⭐⭐⭐⭐⭐",
    playStoreRating4Title = "Romba Nalla Irukku! 4 Stars ⭐⭐⭐⭐",
    playStoreRating3Title = "Nalladhu, improvements thevai ⭐⭐⭐",
    playStoreRatingLowTitle = "Eppadi improve pannalam sollunga ⭐",
    rateOnPlayStore = "Google Play-la Rate Pannunga",
    submitFeedback = "Feedback Anupu",
    remindMeLater = "Apram Remind Pannu",
    notNow = "Ippo Vendam",
    feedbackPrompt = "VoiceKadai-la enna features add panna nalla irukkum?",
    feedbackPlaceholder = "Unga suggestions, voice commands thevaigalai inge type pannunga...",
    feedbackSentToast = "Nandri! Unga feedback VoiceKadai-ah nalla improve panna help pannum. 🙏",
    ratePlayStoreCardTitle = "Google Play-la Rate Pannunga",
    ratePlayStoreCardSubtitle = "Kirana & MSME kadai merchants-ku Voice AI support pannunga"
)

val HindiStrings = AppStrings(
    appName = "VoiceKadai (वॉयसकडई)",
    home = "होम",
    khata = "खाता बही",
    expenses = "खर्चे",
    reminders = "रिमाइंडर",
    settings = "सेटिंग्स",
    subscription = "सब्सक्रिप्शन",
    aiAssistant = "AI सहायक",
    blueprint = "ब्लूप्रिंट",
    cancel = "रद्द करें",
    save = "सहेजें",
    done = "हो गया",
    delete = "हटाएं",
    edit = "संपादित करें",
    search = "खोजें",
    all = "सभी",
    back = "पीछे",
    submit = "जमा करें",
    optional = "वैकल्पिक",
    pro = "प्रो",
    free = "मुफ़्त",
    active = "सक्रिय",

    // Auth
    signInTitle = "अपने मर्चेंट खाते में साइन इन करें",
    signInSubtitle = "अपनी आवाज़ खाता, लेज़र और UPI रिमाइंडर सभी डिवाइस पर सिंक करें",
    signInGoogle = "Google से साइन इन करें",
    signInGoogleDesc = "अपने व्यक्तिगत Google खाते का उपयोग करें (मुफ़्त योजना)",
    signInMicrosoft = "Microsoft से साइन इन करें",
    enterPhone = "मोबाइल नंबर (WhatsApp/UPI)",
    sendOtp = "लॉगिन OTP भेजें",
    verifyOtp = "OTP सत्यापित करें और दुकान खोलें",
    enterOtp = "4-अंकों का SMS OTP दर्ज करें",
    enterStoreName = "आपकी दुकान का नाम",
    enterOwnerName = "आपका नाम (मालिक)",
    enterEmail = "ईमेल पता",
    continueWithAccount = "दुकान में प्रवेश करें",
    exploreDemoStore = "डेमो दुकान देखें (अतिथि मोड)",
    authTagline = "बोलकर व्यापार करें। हिसाब-किताब हम संभालेंगे।",
    authBadge = "भारतीय किराना और छोटे व्यापारियों के लिए निर्मित",

    // Dashboard
    todaySales = "आज की बिक्री",
    cashInflow = "नकद मिला (जमा)",
    pendingUdhaar = "बाकी उधारी (लेना है)",
    advanceToGive = "अग्रिम भुगतान (देना है)",
    quickActions = "त्वरित कार्य",
    recordSale = "बिक्री दर्ज करें",
    recordExpense = "खर्च जोड़ें",
    sendWhatsAppReminder = "रिमाइंडर भेजें",
    recentTransactions = "हाल के लेन-देन",
    viewAll = "सभी देखें",
    noTransactionsYet = "आज अभी तक कोई लेन-देन दर्ज नहीं हुआ है।",
    tapMicToSpeak = "माइक दबाएं और अपनी भाषा में बोलें",
    micCtaHint = "उदा: 'रमेश 500 उधारी', 'सुरेश ने 1200 नकद दिया'",
    topDebtors = "सबसे ज्यादा बाकी उधारी वाले ग्राहक",

    // Khata
    customersTitle = "ग्राहक खाता निर्देशिका",
    searchCustomerHint = "ग्राहक का नाम या फोन नंबर खोजें...",
    filterAll = "सभी",
    filterUdhaar = "बाकी उधारी",
    filterAdvance = "अग्रिम",
    filterSettled = "चुकता (₹0)",
    addCustomer = "नया ग्राहक जोड़ें",
    customerName = "ग्राहक का नाम",
    phoneNumber = "फोन नंबर",
    openingBalance = "प्रारंभिक शेष (₹)",
    notes = "टिप्पणी (पता, गली आदि)",
    balanceDue = "कुल बाकी उधारी",
    advanceBalance = "अग्रिम राशि",
    settledAccount = "हिसाब चुकता (₹0)",
    call = "कॉल करें",
    whatsapp = "व्हाट्सएप",
    noCustomersFound = "कोई ग्राहक नहीं मिला।",

    // Customer Detail
    gaveCredit = "उधारी दी (दिया -)",
    gotPayment = "भुगतान प्राप्त हुआ (मिला +)",
    transactionHistory = "लेन-देन का इतिहास",
    sendPaymentReminder = "व्हाट्सएप पर पेमेंट लिंक भेजें",
    settleAccount = "पूरा हिसाब चुकता करें",
    enterAmount = "राशि दर्ज करें (₹)",
    recordEntry = "प्रविष्टि सहेजें",
    enterNote = "विवरण (उदा: चावल 5 किलो, तेल)",

    // Expenses
    expensesTitle = "व्यापारिक खर्चे",
    todayExpenseTotal = "आज का खर्च",
    totalExpenseMonth = "कुल खर्चे",
    addExpenseTitle = "दुकान का खर्च दर्ज करें",
    expenseCategory = "खर्च की श्रेणी",
    paymentMode = "भुगतान का प्रकार",
    catStock = "सामान व माल (स्टॉक)",
    catRent = "दुकान का किराया",
    catElectricity = "बिजली व बिल",
    catTea = "चाय, नाश्ता व भोजन",
    catTransport = "किराया व डिलीवरी",
    catSalary = "कर्मचारी का वेतन",
    catOther = "अन्य विविध खर्चे",

    // Reminders
    remindersTitle = "स्मार्ट उधारी रिमाइंडर",
    pendingReminders = "लंबित रिमाइंडर",
    completedReminders = "पूर्ण हुए",
    scheduleReminder = "रिमाइंडर सेट करें",
    markAsDone = "पूर्ण चिह्नित करें",
    sendViaWhatsApp = "व्हाट्सएप द्वारा भेजें",

    // AI Chat
    aiTitle = "AI व्यापार सहायक",
    aiSubtitle = "सटीक वित्तीय जानकारी और रिपोर्ट",
    aiPromptHint = "हिंदी में अपनी दुकान के बारे में पूछें...",
    promptProfit = "आज का कुल मुनाफा कितना है?",
    promptTopDebtors = "सबसे ज्यादा उधारी किसकी बाकी है?",
    promptWeeklySales = "इस सप्ताह की बिक्री का सारांश",
    promptExpensesBreakdown = "आज के खर्चों का विवरण",
    clearChat = "चैट साफ़ करें",

    // Subscription
    subscriptionTitle = "सब्सक्रिप्शन योजनाएं",
    freePlanName = "मुफ़्त योजना",
    freePlanPrice = "₹0",
    freePlanCycle = "हमेशा मुफ़्त",
    freePlanFeat1 = "50 वॉयस कमांड प्रति माह",
    freePlanFeat2 = "बुनियादी ग्राहक रिकॉर्ड",
    freePlanFeat3 = "बुनियादी डैशबोर्ड",
    proPlanName = "प्रो योजना",
    proPlanPrice = "₹299",
    proPlanAnnual = "₹2,499",
    proPlanCycle = "/माह",
    proPlanFeat1 = "असीमित वॉयस कमांड",
    proPlanFeat2 = "AI व्यापार रिपोर्ट",
    proPlanFeat3 = "स्मार्ट रिमाइंडर",
    proPlanFeat4 = "उन्नत एनालिटिक्स",
    proPlanFeat5 = "कई भाषाओं का समर्थन",
    bizPlanName = "बिज़नेस योजना",
    bizPlanPrice = "₹999",
    bizPlanAnnual = "₹7,999",
    bizPlanCycle = "/माह",
    bizPlanFeat1 = "एकाधिक कर्मचारी",
    bizPlanFeat2 = "एकाधिक डिवाइस लाइव सिंक",
    bizPlanFeat3 = "उन्नत रिपोर्ट",
    bizPlanFeat4 = "क्लाउड डेटा बैकअप",
    bizPlanFeat5 = "व्यापार एनालिटिक्स",
    monthlyBilling = "मासिक बिलिंग",
    annualBilling = "वार्षिक (30% बचत)",
    subscribeNow = "योजना सब्सक्राइब करें",
    currentActivePlan = "वर्तमान सक्रिय योजना",
    playStorePayoutNotice = "Play Store पर प्रकाशित होने पर, इन-ऐप सब्सक्रिप्शन का भुगतान सीधे डेवलपर के बैंक खाते में जमा होता है।",

    // Settings
    settingsTitle = "दुकान और खाता सेटिंग्स",
    profileSection = "मर्चेंट प्रोफ़ाइल",
    languageSection = "आवाज़ और ऐप प्रदर्शन भाषा",
    safetyGateTitle = "Zero-Hallucination सुरक्षा गेट",
    safetyGateSubtitle = "लेज़र में सहेजने से पहले दृश्य सत्यापन",
    signOutButton = "साइन आउट / खाता बदलें",
    signOutDialogTitle = "VoiceKadai से साइन आउट करें?",
    signOutDialogText = "आपका ऑफ़लाइन डेटा सुरक्षित रूप से संग्रहीत रहेगा।",

    // Play Store Review
    playStoreReviewTitle = "क्या आपको VoiceKadai पसंद आ रहा है?",
    playStoreReviewSubtitle = "आप 1 मिनट से अधिक समय से VoiceKadai का उपयोग कर रहे हैं! यदि यह आपकी दुकान के लिए उपयोगी है, तो कृपया Google Play पर 5-Star रेटिंग दें।",
    playStoreRating5Title = "बहुत पसंद आया! 5 Stars ⭐⭐⭐⭐⭐",
    playStoreRating4Title = "शानदार ऐप! 4 Stars ⭐⭐⭐⭐",
    playStoreRating3Title = "अच्छा है, सुधार की आवश्यकता है ⭐⭐⭐",
    playStoreRatingLowTitle = "सुधार के लिए अपनी राय दें ⭐",
    rateOnPlayStore = "Google Play पर रेटिंग दें",
    submitFeedback = "फीडबैक भेजें",
    remindMeLater = "बाद में याद दिलाएं",
    notNow = "अभी नहीं",
    feedbackPrompt = "हम VoiceKadai को आपकी दुकान के लिए और बेहतर कैसे बना सकते हैं?",
    feedbackPlaceholder = "अपने सुझाव, वॉयस कमांड आवश्यकताएं यहाँ लिखें...",
    feedbackSentToast = "धन्यवाद! आपकी प्रतिक्रिया VoiceKadai को बेहतर बनाने में मदद करेगी। 🙏",
    ratePlayStoreCardTitle = "Google Play पर रेटिंग दें",
    ratePlayStoreCardSubtitle = "किराना और छोटे व्यापारियों के लिए वॉयस AI का समर्थन करें"
)

val LocalAppStrings = compositionLocalOf { EnglishStrings }
